[phases.setup]
nixPkgs = ["dotnet-sdk_9"]

[phases.build]
cmds = [
  "dotnet restore hng-genderizeApp.sln",
  "dotnet publish hng-genderizeApp/hng-genderizeApp.csproj --no-restore -c Release -o out"
]

[start]
cmd = "sh start.sh"
